#!/bin/bash

docker build --tag "$IMAGE_NAME" -f Dockerfile.build .
if [ "$TRAVIS_BRANCH" == "development" ]; then
    sha="$(git rev-parse --short HEAD)"
    docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:development"
    docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:dev-${sha}"
    docker push "${IMAGE_NAME}:development" && docker push "${IMAGE_NAME}:dev-${sha}"
elif [ "$1" == "master" ] && [ -n "$TRAVIS_TAG" ]; then
    docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
    docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${TRAVIS_TAG}"
    docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
fi

